Helpers images assets
andrerferrer/packman pull request #5
Opened 2020-06-09 17:29 UTC by caiazzo14

Refactored Home code to use link_to and image_tag to generate links dynamically and pointing to the assets folder for the images. Commented what was done to explain.

2020-06-09 17:30 UTC, caiazzo14 commented
@obrenoco , I used two helpers on this. The code is commented so you can check them out

2020-06-10 04:07 UTC, obrenoco commented on app/assets/images/logos/busch-gardens-4200.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="2500" height="2500" viewBox="0 0 192.756 192.756"><g fill-rule="evenodd" clip-rule="evenodd"><path fill="#fff" d="M0 0h192.756v192.756H0V0z"/><path d="M
Para Deploy, essas imagens podem estar aqui na pasta 'app' ou deverão ser movidas para a pasta 'public' ?

2020-06-12 20:22 UTC, andrerferrer commented on app/assets/images/logos/busch-gardens-4200.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="2500" height="2500" viewBox="0 0 192.756 192.756"><g fill-rule="evenodd" clip-rule="evenodd"><path fill="#fff" d="M0 0h192.756v192.756H0V0z"/><path d="M
podem estar aí mesmo. Sem erro

2020-06-12 20:24 UTC, andrerferrer requested changes
@caiazzo14 pls continue from here

2020-06-12 20:24 UTC, andrerferrer commented on .vscode/settings.json
> +{
Pq isso ta aqui?

2020-06-12 20:24 UTC, andrerferrer commented on app/assets/stylesheets/pages/_home.scss
>  depois refatoramos, talkey?*/
esse arquivo inteiro foi comentado no outro PR

2020-06-13 04:15 UTC, obrenoco commented on .vscode/settings.json
> +{
solved

2020-06-13 13:40 UTC, obrenoco approved these changes

2020-06-13 14:54 UTC, andrerferrer approved these changes
Parece tudo certo.
@caiazzo14 any final words?

2020-06-13 15:15 UTC, merged

2020-06-13 15:31 UTC, andrerferrer commented
@obrenoco , o @caiazzo14 tinha dado o review dele? Pq vc deu o merge?

2020-06-13 15:41 UTC, andrerferrer commented
@caiazzo14 , abre outro pull request pra dar merge na branch `html-build`. E não na master